# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from deepracer_msgs/Control_input.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Control_input(genpy.Message):
  _md5sum = "ee15870a09046e7814ea809ce3c9164e"
  _type = "deepracer_msgs/Control_input"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 Throttle
float64 angle
int8 Emergency_stops
"""
  __slots__ = ['Throttle','angle','Emergency_stops']
  _slot_types = ['float64','float64','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Throttle,angle,Emergency_stops

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Control_input, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Throttle is None:
        self.Throttle = 0.
      if self.angle is None:
        self.angle = 0.
      if self.Emergency_stops is None:
        self.Emergency_stops = 0
    else:
      self.Throttle = 0.
      self.angle = 0.
      self.Emergency_stops = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2db().pack(_x.Throttle, _x.angle, _x.Emergency_stops))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.Throttle, _x.angle, _x.Emergency_stops,) = _get_struct_2db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2db().pack(_x.Throttle, _x.angle, _x.Emergency_stops))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.Throttle, _x.angle, _x.Emergency_stops,) = _get_struct_2db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2db = None
def _get_struct_2db():
    global _struct_2db
    if _struct_2db is None:
        _struct_2db = struct.Struct("<2db")
    return _struct_2db
